### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

# Criar um array com 10 números inteiros aleatórios entre 1 e 50
arr = np.random.randint(1, 51, size=10)

# Calcular a média e o desvio padrão do array
mean_value = np.mean(arr)
std_value = np.std(arr)

# Exibir os resultados
print("Array: ", arr)
print("Média: ", mean_value)
print("Desvio padrão: ", std_value)

Array:  [ 3 15  2 26 48 43 12 27  4 14]
Média:  19.4
Desvio padrão:  15.454449197561198


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
import numpy as np

# Criar um array com 10 números aleatórios
arr = np.random.rand(10)

# Calcular a raiz quadrada dos valores menores ou iguais a 0,5
arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])

print(arr)

[0.2361678  0.97150205 0.92737496 0.45585486 0.50066647 0.40952259
 0.61965376 0.2790174  0.83763743 0.58239397]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
import numpy as np

# Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios
matriz_3d = np.random.rand(3, 3, 3)

# Exibir o valor máximo de cada linha de cada matriz 2D dentro da matriz 3D
max_values = np.amax(matriz_3d, axis=1)

# Exibir os resultados
print("Matriz 3D:\n", matriz_3d)
print("Valores máximos de cada linha de cada matriz 2D:\n", max_values)

Matriz 3D:
 [[[0.36160083 0.11641002 0.53131174]
  [0.00838915 0.76160844 0.78278698]
  [0.49969742 0.97584997 0.60358255]]

 [[0.97779519 0.78227642 0.12058545]
  [0.46557393 0.52565893 0.54379792]
  [0.87505573 0.4845887  0.44668604]]

 [[0.70843945 0.79769631 0.40469915]
  [0.47235729 0.32277855 0.54565075]
  [0.45289306 0.25221733 0.99775425]]]
Valores máximos de cada linha de cada matriz 2D:
 [[0.49969742 0.97584997 0.78278698]
 [0.97779519 0.78227642 0.54379792]
 [0.70843945 0.79769631 0.99775425]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
import numpy as np

# Criar uma matriz de tamanho 5x5 com valores aleatórios
matriz = np.random.rand(5, 5)

# Subtrair a média de cada linha da matriz
# axis=1 --> a linha
# axis=0 --> a coluna
media = np.mean(matriz, axis=1)
matriz_linha_media = matriz - media[:, np.newaxis]

print("Matriz original:\n", matriz)
print("Média de cada linha:\n", media)
print("Matriz com a média de cada linha subtraída:\n", matriz_linha_media)

Matriz original:
 [[0.67463859 0.21331961 0.9828996  0.0370389  0.8683583 ]
 [0.27413833 0.28646082 0.82059618 0.79152481 0.76010166]
 [0.44204244 0.06981984 0.58652796 0.31916632 0.27846712]
 [0.88887369 0.51009245 0.56308721 0.96393471 0.82688045]
 [0.61625605 0.65785897 0.64596723 0.9226386  0.68998607]]
Média de cada linha:
 [0.555251   0.58656436 0.33920474 0.7505737  0.70654138]
Matriz com a média de cada linha subtraída:
 [[ 0.11938759 -0.34193139  0.4276486  -0.5182121   0.3131073 ]
 [-0.31242603 -0.30010354  0.23403182  0.20496045  0.1735373 ]
 [ 0.1028377  -0.26938489  0.24732322 -0.02003842 -0.06073762]
 [ 0.13829999 -0.24048125 -0.1874865   0.21336101  0.07630674]
 [-0.09028533 -0.04868242 -0.06057415  0.21609722 -0.01655532]]


In [0]:
(0.67463859 + 0.21331961 + 0.9828996 + 0.0370389 + 0.8683583)/5

Out[5]: 0.5552509999999999

In [0]:
(0.27413833 + 0.28646082 + 0.82059618 + 0.79152481 + 0.76010166)/5

Out[6]: 0.58656436

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

# Criar uma matriz de tamanho 4x4 com valores aleatórios
matriz = np.random.rand(4, 4)

# Calcular a média e o desvio padrão das diagonais da matriz
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

# Exibir os resultados
print("Matriz:\n", matriz)
print("Diagonal principal:\n", diag_principal)
print("Diagonal secundária:\n", diag_secundaria)
print("Média das diagonais:", media_diag)
print("Desvio padrão das diagonais:", std_diag)

Matriz:
 [[0.80025318 0.26922651 0.85552243 0.96033053]
 [0.60553089 0.63770041 0.19799706 0.44614318]
 [0.15226167 0.69236689 0.1628544  0.12431936]
 [0.93654516 0.19672196 0.49885891 0.44535384]]
Diagonal principal:
 [0.80025318 0.63770041 0.1628544  0.44535384]
Diagonal secundária:
 [0.96033053 0.19799706 0.69236689 0.93654516]
Média das diagonais: 0.6041751822606009
Desvio padrão das diagonais: 0.28931679328057774
