### NUMPY

In [0]:
import numpy as np

arr = np.random.rand(10)

min_value = np.min(arr)
max_value = np.max(arr)

print("Array: ", arr)
print("Valor mínimo: ", min_value)
print("Valor máximo: ", max_value)

Array:  [0.79927689 0.56458375 0.61857615 0.6907088  0.10301751 0.95699837
 0.20390952 0.17986894 0.94856347 0.77299236]
Valor mínimo:  0.10301751003588844
Valor máximo:  0.9569983710057125


In [0]:
import numpy as np

arr = np.random.rand(10)

# Substituir os valores maiores que 0,5 por 1 e os valores menores ou iguais a 0,5 por 0
arr[arr > 0.5] = 1
arr[arr <= 0.5] = 0

print(arr)

[1. 0. 1. 1. 1. 1. 1. 0. 1. 1.]


In [0]:
import numpy as np

matriz = np.random.rand(3, 3)

# Calcular a matriz transposta
matriz_transposta = np.transpose(matriz)


print("Matriz original:\n", matriz)
print("Matriz transposta:\n", matriz_transposta)

Matriz original:
 [[0.1693411  0.48142256 0.90083056]
 [0.46358962 0.15655188 0.53907807]
 [0.45945585 0.9939633  0.18108644]]
Matriz transposta:
 [[0.1693411  0.46358962 0.45945585]
 [0.48142256 0.15655188 0.9939633 ]
 [0.90083056 0.53907807 0.18108644]]


In [0]:
import numpy as np

arr = np.random.rand(10)

# Calcular a média móvel com janela de tamanho 3
janela = 3
media_movel = np.convolve(arr, np.ones(janela) / janela, mode='valid')

print("Array original:", arr)
print("Média móvel com janela de tamanho", janela, ":", media_movel)

Array original: [0.36986279 0.03135223 0.57738094 0.45203946 0.83472818 0.4908499
 0.39363465 0.41792549 0.45407649 0.28557101]
Média móvel com janela de tamanho 3 : [0.32619865 0.35359088 0.62138286 0.59253918 0.57307091 0.43413668
 0.42187888 0.38585767]
